# Generated by Django 5.2.4 on 2025-07-15 08:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('upload_type', models.CharField(choices=[('depot_departures', '1. Depot Departures Information'), ('customer_timestamps', '2. Customer Timestamps'), ('distance_info', '3. Distance Information'), ('timestamps_duration', '4. Timestamps and Duration'), ('avg_time_route', '5. Average Time in Route'), ('time_route_info', '6. Time in Route Information'), ('other', 'Other CSV File')], max_length=50)),
                ('file', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx', 'xls'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductivitySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('transporter', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('total_loads', models.IntegerField(default=0)),
                ('total_distance', models.FloatField(blank=True, null=True)),
                ('total_time', models.FloatField(blank=True, null=True)),
                ('avg_efficiency_score', models.FloatField(blank=True, null=True)),
                ('on_time_deliveries', models.IntegerField(default=0)),
                ('delayed_deliveries', models.IntegerField(default=0)),
                ('early_deliveries', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_range_end'],
            },
        ),
        migrations.CreateModel(
            name='TruckPerformanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField()),
                ('month_name', models.CharField(max_length=20)),
                ('transporter', models.CharField(max_length=100)),
                ('load_number', models.CharField(max_length=50)),
                ('mode_of_capture', models.CharField(max_length=50)),
                ('driver_name', models.CharField(max_length=100)),
                ('truck_number', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=100)),
                ('dj_departure_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_at_depot', models.DateTimeField(blank=True, null=True)),
                ('ave_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('d1', models.FloatField(blank=True, help_text='Distance 1', null=True)),
                ('d2', models.FloatField(blank=True, help_text='Distance 2', null=True)),
                ('d3', models.FloatField(blank=True, help_text='Distance 3', null=True)),
                ('d4', models.FloatField(blank=True, help_text='Distance 4', null=True)),
                ('comment_ave_tir', models.TextField(blank=True, help_text='Comment AVE TIR', null=True)),
                ('total_distance', models.FloatField(blank=True, null=True)),
                ('total_time', models.FloatField(blank=True, null=True)),
                ('efficiency_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('csv_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_data', to='dashboard.csvupload')),
            ],
            options={
                'verbose_name': 'Truck Performance Data',
                'verbose_name_plural': 'Truck Performance Data',
                'ordering': ['-create_date', 'transporter', 'load_number'],
                'unique_together': {('load_number', 'create_date', 'truck_number')},
            },
        ),
    ]
