# Generated by Django 5.2.4 on 2025-07-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckperformancedata',
            name='arrival_at_customer',
            field=models.DateTimeField(blank=True, help_text='Arrival At Customer', null=True),
        ),
        migrations.AddField(
            model_name='truckperformancedata',
            name='ave_departure',
            field=models.IntegerField(blank=True, help_text='AVE Departure', null=True),
        ),
        migrations.AddField(
            model_name='truckperformancedata',
            name='comment_ave_departure',
            field=models.TextField(blank=True, help_text='Comment AVE Departure', null=True),
        ),
        migrations.AddField(
            model_name='truckperformancedata',
            name='comment_tat',
            field=models.TextField(blank=True, help_text='Comment TAT (Turn Around Time)', null=True),
        ),
        migrations.AddField(
            model_name='truckperformancedata',
            name='delivery_time',
            field=models.FloatField(blank=True, help_text='Time from departure to customer arrival (hours)', null=True),
        ),
        migrations.AddField(
            model_name='truckperformancedata',
            name='departure_deviation_min',
            field=models.IntegerField(blank=True, help_text='Departure Deviation (min)', null=True),
        ),
        migrations.AddField(
            model_name='truckperformancedata',
            name='departure_time_from_customer',
            field=models.DateTimeField(blank=True, help_text='Departure Time from Customer', null=True),
        ),
        migrations.AddField(
            model_name='truckperformancedata',
            name='service_time_at_customer',
            field=models.IntegerField(blank=True, help_text='Service Time At Customer (minutes)', null=True),
        ),
        migrations.AlterField(
            model_name='truckperformancedata',
            name='arrival_at_depot',
            field=models.DateTimeField(blank=True, help_text='Arrival At Depot', null=True),
        ),
        migrations.AlterField(
            model_name='truckperformancedata',
            name='ave_arrival_time',
            field=models.IntegerField(blank=True, help_text='AVE Arrival Time', null=True),
        ),
        migrations.AlterField(
            model_name='truckperformancedata',
            name='customer_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='truckperformancedata',
            name='dj_departure_time',
            field=models.DateTimeField(blank=True, help_text='DJ Departure Time', null=True),
        ),
        migrations.AlterField(
            model_name='truckperformancedata',
            name='efficiency_score',
            field=models.FloatField(blank=True, help_text='Distance per hour (km/h)', null=True),
        ),
        migrations.AlterField(
            model_name='truckperformancedata',
            name='mode_of_capture',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='truckperformancedata',
            name='total_distance',
            field=models.FloatField(blank=True, help_text='Total Distance (D1+D2+D3+D4)', null=True),
        ),
        migrations.AlterField(
            model_name='truckperformancedata',
            name='total_time',
            field=models.FloatField(blank=True, help_text='Total time from departure to depot arrival (hours)', null=True),
        ),
    ]
