# Generated by Django 5.2.4 on 2025-07-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_truckperformancedata_arrival_at_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckperformancedata',
            name='current_status',
            field=models.CharField(choices=[('pending', 'Pending Departure'), ('departed', 'Departed from Depot'), ('in_transit', 'In Transit to Customer'), ('at_customer', 'At Customer Location'), ('servicing', 'Servicing Customer'), ('returning', 'Returning to Depot'), ('completed', 'Journey Completed'), ('delayed', 'Delayed')], default='pending', max_length=20),
        ),
    ]
