# Generated by Django 5.2.4 on 2025-07-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_truckperformancedata_current_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckperformancedata',
            name='clockin_time',
            field=models.DateTimeField(blank=True, help_text='Clock-In Time', null=True),
        ),
        migrations.AlterField(
            model_name='csvupload',
            name='upload_type',
            field=models.CharField(choices=[('depot_departures', '1. Depot Departures Information'), ('customer_timestamps', '2. Customer Timestamps'), ('distance_info', '3. Distance Information'), ('timestamps_duration', '4. Timestamps and Duration'), ('time_route_info', '6. Time in Route Information'), ('other', 'Other CSV File')], max_length=50),
        ),
    ]
