# Generated by Django 5.2.4 on 2025-07-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_truckperformancedata_clockin_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckperformancedata',
            name='planned_departure_time',
            field=models.DateTimeField(blank=True, help_text='Planned Departure Time', null=True),
        ),
    ]
