# Generated by Django 5.2.4 on 2025-07-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_truckperformancedata_planned_departure_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckperformancedata',
            name='budgeted_kms',
            field=models.FloatField(blank=True, help_text='Planned distance to customer (from distance info)', null=True),
        ),
    ]
