# Generated by Django 5.2.4 on 2025-07-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_truckperformancedata_budgeted_kms'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckperformancedata',
            name='km_deviation',
            field=models.FloatField(blank=True, help_text='Difference between budgeted_kms and total_distance', null=True),
        ),
    ]
