# Generated by Django 5.2.4 on 2025-07-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_truckperformancedata_km_deviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckperformancedata',
            name='clock_out',
            field=models.DateTimeField(blank=True, help_text='Time when load was completed (from LoadCompleted in timestamps file)', null=True),
        ),
    ]
