# Generated by Django 5.2.4 on 2025-07-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_truckperformancedata_clock_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckperformancedata',
            name='actual_days_in_route',
            field=models.FloatField(blank=True, help_text='Actual days in route (from departure to completion)', null=True),
        ),
    ]
