# Generated by Django 5.2.4 on 2025-07-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_truckperformancedata_actual_days_in_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckperformancedata',
            name='bud_days_in_route',
            field=models.FloatField(blank=True, help_text='Budgeted days in route (from planned DJ data)', null=True),
        ),
    ]
