# Generated by Django 5.2.4 on 2025-07-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_truckperformancedata_bud_days_in_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckperformancedata',
            name='days_in_route_deviation',
            field=models.FloatField(blank=True, help_text='Deviation between actual and budgeted days in route', null=True),
        ),
    ]
