# Generated by Django 5.2.4 on 2025-07-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_truckperformancedata_days_in_route_deviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckperformancedata',
            name='total_hour_route',
            field=models.FloatField(blank=True, help_text='Total hours in route (from departure to completion)', null=True),
        ),
    ]
