# Generated by Django 5.2.4 on 2025-07-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_truckperformancedata_total_hour_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckperformancedata',
            name='driver_rest_hours_in_route',
            field=models.FloatField(blank=True, help_text='Total driver rest hours in route (if available)', null=True),
        ),
        migrations.AddField(
            model_name='truckperformancedata',
            name='total_working_hours',
            field=models.FloatField(blank=True, help_text='Total working hours in route (from data or calculated)', null=True),
        ),
    ]
