# Generated by Django 5.2.4 on 2025-07-25 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_truckperformancedata_driver_rest_hours_in_route_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truckperformancedata',
            name='d1',
        ),
        migrations.RemoveField(
            model_name='truckperformancedata',
            name='d2',
        ),
        migrations.RemoveField(
            model_name='truckperformancedata',
            name='d3',
        ),
        migrations.RemoveField(
            model_name='truckperformancedata',
            name='d4',
        ),
    ]
