# Generated by Django 5.2.4 on 2025-12-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_truckperformancedata_d1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckperformancedata',
            name='d1',
            field=models.FloatField(blank=True, help_text='Distance 1', null=True),
        ),
        migrations.AddField(
            model_name='truckperformancedata',
            name='d2',
            field=models.FloatField(blank=True, help_text='Distance 2', null=True),
        ),
        migrations.AddField(
            model_name='truckperformancedata',
            name='d3',
            field=models.FloatField(blank=True, help_text='Distance 3', null=True),
        ),
        migrations.AddField(
            model_name='truckperformancedata',
            name='d4',
            field=models.FloatField(blank=True, help_text='Distance 4', null=True),
        ),
    ]
