# Generated by Django 5.2.4 on 2025-12-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_truckperformancedata_d1_truckperformancedata_d2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckperformancedata',
            name='planned_arrival_time',
            field=models.DateTimeField(blank=True, help_text='Planned Arrival Time at Depot', null=True),
        ),
        migrations.AddField(
            model_name='truckperformancedata',
            name='tlp_vol_hl',
            field=models.FloatField(blank=True, help_text='TLP Volume HL', null=True),
        ),
    ]
