# Generated by Django 5.2.4 on 2025-12-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_add_planned_arrival_time_and_tlp'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckperformancedata',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Employee/Driver ID', max_length=50, null=True),
        ),
    ]
